### ISSUE TITLE
Projeto de Interface - User Flow

### ISSUE THREAD

**Issue by leandroborth** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t5-finanfy#12]

**Comment by RodollfoAlmeida** [comment]
https://lucid.app/lucidchart/b6909bf0-0ed4-4a5b-883e-dd3e453e5351/edit?invitationId=inv_790f0a08-5a0b-4541-886b-b0ba52f20e1d&page=0_0#

https://rp.mockplus.com/editor/F9h1wgLB6H/cl9Z_E0pzkb
